import'../../../packages/core/src/ui.css';import'./style.css';import en from'../locales/en.json';
import{createScorm}from'../../../packages/core/src/scorm.ts';import{createTranslator}from'../../../packages/core/src/locale.ts';
import{MAX_REVIEWS,REGIONS,canFinalize,canMarkConcern,decide,expectedDecision,fresh,integrity,mismatch,outcome,regionById,restore,reviewFor,reviewedMismatchCount,type Decision,type EvidenceLayer,type GameState,type Region,type RegionId}from'./rules.ts';

const dictionaries=Object.fromEntries(Object.entries(import.meta.glob<Record<string,string>>('../locales/*.json',{eager:true,import:'default'})).map(([path,messages])=>[path.match(/\/([^/]+)\.json$/)?.[1]??'en',messages]));
const{t,locale}=createTranslator(en,dictionaries),scorm=createScorm('m4-1-blind-spot'),app=document.querySelector<HTMLDivElement>('#app')!;document.documentElement.lang=locale;document.title=`Drone4Build · ${t('title')}`;
let state=restore(scorm.load<GameState>())??fresh(),helpOpen=false,evidenceZoom=1;
const esc=(value:string|number)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const tx=(key:string,values?:Record<string,string|number>)=>esc(t(key,values));const save=()=>scorm.save(state);

function header(){return`<header class="app-header"><div class="brand"><span class="brand-block">D<span>4</span>B</span><div><small>${tx('course')}</small><strong>${tx('title')} <i>${tx('subtitle')}</i></strong></div></div><div class="head-actions">${state.phase==='audit'?`<button data-action="help">? ${tx('help.open')}</button>`:''}<span class="mode"><i></i>${tx(scorm.snapshot().mode==='mock'?'mode.mock':'mode.lms')}</span></div></header>`;}
function toolDiagram(){return`<div class="tool-diagram">${(['raw','ai','context','focus']as const).map((tool,i)=>`<div><span>${i===0?'▧':i===1?'⌗':i===2?'◎':'◉'}</span><strong>${tx(`tool.${tool}`)}</strong><small>${tx(`tool.${tool}Help`)}</small></div>`).join('')}<div><span>◐</span><strong>${tx('tool.overlay')}</strong><small>${tx('tool.overlayHelp')}</small></div></div>`;}
function intro(){return`<div class="blind-shell">${header()}<main class="intro-stage"><div class="intro-backdrop">${building(false)}</div><section class="intro-card"><div class="project-chip"><span>${tx('project.name')}</span><small>${tx('project.desc')}</small></div><div class="eyebrow">${tx('intro.eyebrow')}</div><h1>${tx('intro.title')}</h1><p>${tx('intro.body')}</p><div class="role-objective"><div><span>${tx('role.label')}</span><strong>${tx('role.name')}</strong></div><p>${tx('intro.objective')}</p></div><div class="principle"><b>!</b><span>${tx('intro.principle')}</span></div>${toolDiagram()}<button class="launch" data-action="start">${tx('intro.start')} <b>→</b></button></section></main></div>`;}

function surfaceDetail(r:Region){
 if(r.surface==='cladding')return`<g class="ribs">${Array.from({length:Math.max(5,Math.floor(r.w/20))},(_,i)=>`<path d="M${r.x+11+i*20} ${r.y+8}V${r.y+r.h-8}"/>`).join('')}<circle cx="${r.x+r.w-18}" cy="${r.y+19}" r="3"/><circle cx="${r.x+r.w-18}" cy="${r.y+r.h-20}" r="3"/></g>`;
 if(r.surface==='window')return`<rect class="window" x="${r.x+17}" y="${r.y+30}" width="${r.w-34}" height="${r.h-53}"/><path class="mullion" d="M${r.x+r.w/2} ${r.y+30}V${r.y+r.h-23}"/>`;
 if(r.surface==='plinth')return`<path class="plinth-lines" d="M${r.x+12} ${r.y+18}H${r.x+r.w-12}M${r.x+12} ${r.y+37}H${r.x+r.w-12}"/>`;
 const windows=r.id==='p3'?3:2,margin=18,gap=9,ww=(r.w-margin*2-gap*(windows-1))/windows;
 return`<g class="windows">${Array.from({length:windows},(_,i)=>`<rect x="${r.x+margin+i*(ww+gap)}" y="${r.y+39}" width="${ww}" height="${r.h-65}"/>`).join('')}</g><path class="panel-joint" d="M${r.x+10} ${r.y+27}H${r.x+r.w-10}"/>`;
}
function aiMark(r:Region){if(!state.aiOverlay)return'';if(r.ai==='clean')return`<g class="ai-clean"><circle cx="${r.x+r.w-18}" cy="${r.y+19}" r="8"/><path d="M${r.x+r.w-22} ${r.y+19}l3 3 6-7"/><text x="${r.x+9}" y="${r.y+r.h-9}">${tx('board.clean')} · ${r.confidence}%</text></g>`;
 const cx=r.x+r.w*.54,cy=r.y+r.h*.53,bw=Math.min(77,r.w*.45),bh=Math.min(82,r.h*.48);return`<g class="ai-detection"><rect x="${cx-bw/2}" y="${cy-bh/2}" width="${bw}" height="${bh}"/><path d="M${cx-bw/2+13} ${cy-bh/2}h-13v13m${bw} 0v-13h-13m${-bw+13} ${bh}h-13v-13m${bw} 0v13h-13"/><text x="${r.x+9}" y="${r.y+r.h-9}">${tx('board.detected')} · ${r.confidence}%</text></g>`;}
function reviewMark(r:Region){const review=reviewFor(state,r.id);if(!review)return`<g class="unreviewed"><circle cx="${r.x+18}" cy="${r.y+18}" r="10"/><text x="${r.x+18}" y="${r.y+22}" text-anchor="middle">${r.sample}</text></g>`;return`<g class="review-mark ${review.decision}"><circle cx="${r.x+r.w-19}" cy="${r.y+r.h-22}" r="14"/><path d="${review.decision==='validate'?`M${r.x+r.w-26} ${r.y+r.h-22}l5 5 10-12`:`M${r.x+r.w-24} ${r.y+r.h-29}v11m0 6v1`}"/></g>`;}
function building(interactive=true){return`<svg class="building-board ${state.aiOverlay?'show-ai':'hide-ai'}" viewBox="0 0 1000 650" style="--board-zoom:${state.boardZoom}" role="group" aria-label="${tx('board.title')}"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#82b1b7"/><stop offset="1" stop-color="#d0d8cc"/></linearGradient><linearGradient id="glass" x2="0" y2="1"><stop stop-color="#163747"/><stop offset=".46" stop-color="#376b77"/><stop offset=".5" stop-color="#a0c2c0"/><stop offset="1" stop-color="#234c58"/></linearGradient><pattern id="concernHatch" width="14" height="14" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><path d="M0 0V14" stroke="#f1b74c" stroke-width="4" opacity=".32"/></pattern><filter id="shadow"><feDropShadow dx="0" dy="13" stdDeviation="11" flood-opacity=".28"/></filter></defs><rect width="1000" height="650" fill="url(#sky)"/><path class="city" d="M0 420h74V278h45v83h52v-49h43v108h85v230H0zm866 0V248h49v72h45v-32h40v362H810V420z"/><path class="ground" d="M0 575L1000 536V650H0Z"/><g class="zoom-layer" filter="url(#shadow)"><path class="building-side" d="M92 121l42 26v470l-42 25z"/><path class="shell" d="M134 108h716l38 35-38 476H134z"/><path class="roof" d="M134 108l38-27h691l25 62-38-35z"/>
 ${REGIONS.map(r=>`<g class="region ${r.surface} ${r.quality} ${state.selected===r.id?'selected':''} ${reviewFor(state,r.id)?.decision??''} ${state.concernMarked&&r.context==='dark-cladding'?'concern':''}" ${interactive?`data-region="${r.id}" role="button" tabindex="0"`:'role="group"'} aria-label="${tx(`region.${r.id}`)}, ${tx(`panel.ai.${r.ai}`,{value:r.confidence})}"><rect class="region-panel" x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}"/>${surfaceDetail(r)}<text class="region-name" x="${r.x+9}" y="${r.y+20}">${tx(`region.${r.id}`)}</text>${aiMark(r)}${reviewMark(r)}</g>`).join('')}
 ${state.concernMarked?`<g class="concern-zone"><path d="M666 120h183v431H500v-218h166z" fill="url(#concernHatch)"/><path d="M666 120h183v431H500v-218h166z"/><text x="842" y="111" text-anchor="end">${tx('board.concern')}</text></g>`:''}<path class="base" d="M122 619h739l-19 25H109z"/></g></svg>`;}

function reportStatus(){if(state.concernMarked)return'hud.concern';if(state.reviews.length>=5)return'hud.ready';return state.reviews.length?'hud.testing':'hud.preliminary';}
function hud(){const remaining=MAX_REVIEWS-state.reviews.length;return`<div class="audit-hud"><div><span>${tx('hud.capacity')}</span><strong>${remaining}<small>/ ${MAX_REVIEWS}</small></strong><div class="capacity-pips">${Array.from({length:MAX_REVIEWS},(_,i)=>`<i class="${i<remaining?'live':''}"></i>`).join('')}</div></div><div><span>${tx('hud.reviewed')}</span><strong>${state.reviews.length}<small>/ 8</small></strong></div><div><span>${tx('hud.report')}</span><strong>${tx(reportStatus())}</strong></div></div>`;}
function boardPanel(){return`<section class="board-panel"><div class="board-head"><div><div class="eyebrow">${tx('board.label')}</div><h1>${tx('board.title')}</h1><p>${tx('project.name')} · ${tx('project.desc')}</p></div><div class="board-tools"><button data-action="ai-toggle">${tx(state.aiOverlay?'board.overlayOn':'board.overlayOff')}</button><button data-action="board-out" aria-label="${tx('board.zoomOut')}">−</button><button data-action="board-in" aria-label="${tx('board.zoomIn')}">＋</button></div></div><div class="building-window">${building()}</div><div class="legend"><span class="detected">${tx('legend.detected')}</span><span class="clean">${tx('legend.clean')}</span><span class="validated">${tx('legend.validated')}</span><span class="flagged">${tx('legend.flagged')}</span><span class="concern">${tx('legend.concern')}</span></div></section>`;}

function rawTexture(r:Region){if(r.surface==='cladding'||r.surface==='plinth')return`${Array.from({length:17},(_,i)=>`<path class="e-rib" d="M${28+i*29} 20V258"/>`).join('')}<path class="bright-joint" d="M273 20V258"/>`;if(r.surface==='window')return`<rect class="e-window" x="38" y="42" width="452" height="195"/><path class="e-mullion" d="M264 42V237M38 139H490"/>`;return`<path class="render-seams" d="M20 91H510M20 182H510M180 20V258M364 20V258"/>`;}
function defect(r:Region){if(r.truth==='clear')return'';const path=r.id==='p3'?'M205 103l30 9 21-15 27 12':r.id==='p7'?'M253 59l-7 44 13 26-11 42 15 48':r.id==='p6'?'M267 51l-11 47 17 31-15 44 13 56':'M260 49l-13 49 17 29-15 41 16 53';return`<path class="raw-defect" d="${path}"/><path class="defect-edge" d="${path}"/>`;}
function mask(r:Region){if(r.mask==='none')return`<g class="no-mask"><circle cx="266" cy="139" r="26"/><path d="M254 139l8 8 17-20"/></g>`;if(r.mask==='fragmented')return`<g class="e-ai"><rect x="187" y="79" width="73" height="48"/><rect x="265" y="122" width="66" height="52"/></g>`;const box=r.mask==='shifted'?{x:287,y:51,w:78,h:177}:r.mask==='oversize'?{x:176,y:34,w:206,h:210}:{x:217,y:45,w:98,h:187};return`<g class="e-ai"><rect x="${box.x}" y="${box.y}" width="${box.w}" height="${box.h}"/><path d="M${box.x+15} ${box.y}h-15v15m${box.w} 0V${box.y}h-15m${-box.w+15} ${box.h}h-15v-15m${box.w} 0v15h-15"/></g>`;}
function evidenceArt(r:Region){const focusX=mismatch(r)?(r.truth==='clear'?315:424):263,context=`${tx(`surface.${r.surface}`)} · ${tx(`quality.${r.quality}`)}`;return`<svg class="evidence-art layer-${state.evidenceLayer} quality-${r.quality}" style="--overlay:${state.overlay}" viewBox="0 0 780 290"><defs><linearGradient id="frameBg" x2="0" y2="1"><stop stop-color="${r.surface==='cladding'||r.surface==='plinth'?'#6d8587':'#a7aea3'}"/><stop offset="1" stop-color="${r.surface==='cladding'||r.surface==='plinth'?'#344f53':'#727b72'}"/></linearGradient><radialGradient id="heat"><stop stop-color="#fff680" stop-opacity=".9"/><stop offset=".4" stop-color="#ff8b42" stop-opacity=".7"/><stop offset="1" stop-color="#df315d" stop-opacity="0"/></radialGradient><filter id="grain"><feTurbulence baseFrequency=".7" numOctaves="2" seed="5" result="n"/><feBlend in="SourceGraphic" in2="n" mode="soft-light"/></filter><clipPath id="frameClip"><rect x="20" y="20" width="500" height="238" rx="4"/></clipPath></defs><g clip-path="url(#frameClip)"><g transform="translate(270 139) scale(${evidenceZoom}) translate(-270 -139)"><rect x="20" y="20" width="500" height="238" fill="url(#frameBg)" filter="url(#grain)"/><g class="raw-surface">${rawTexture(r)}${defect(r)}</g>${mask(r)}<g class="focus-map"><ellipse cx="${focusX}" cy="139" rx="86" ry="112"/><ellipse cx="${focusX+28}" cy="91" rx="48" ry="62"/><circle cx="${focusX-22}" cy="196" r="39"/></g><g class="context-layer"><rect x="20" y="20" width="500" height="238"/><text x="37" y="49">${tx('evidence.context',{surface:tx(`surface.${r.surface}`),quality:tx(`quality.${r.quality}`)})}</text><path d="M38 65H501M38 226H501"/></g></g></g><rect class="reference" x="548" y="42" width="210" height="198" rx="4" fill="url(#frameBg)"/>${r.surface==='cladding'||r.surface==='plinth'?Array.from({length:7},(_,i)=>`<path class="e-rib" d="M${563+i*28} 55V226"/>`).join(''):`<path class="render-seams" d="M560 116H744M638 53V228"/>`}<path class="reference-bracket" d="M563 58h14m-14 0v14m180-14h-14m14 0v14m-180 152h14m-14 0v-14m180 14h-14m14 0v-14"/><text class="frame-label" x="31" y="279">${tx('evidence.raw')}</text><text class="frame-label" x="556" y="279">${tx('evidence.reference')}</text>${r.ai==='clean'&&state.evidenceLayer==='ai'?`<text class="mask-label" x="270" y="145" text-anchor="middle">${tx('evidence.noMask')}</text>`:''}</svg>`;}

function guide(){if(state.reviews.length===0){if(!state.usedLayers.includes('ai'))return tx('guide.first');if(!state.overlayAdjusted)return tx('guide.fade');return tx('guide.decide');}if(state.reviews.length===1)return tx('guide.second');if(reviewedMismatchCount(state)>=2&&!state.concernMarked)return tx('guide.soft');return'';}
function feedbackKey(r:Region,decision:Decision){const kind=outcome(r);return kind==='truePositive'?(decision==='validate'?'feedback.tpValidated':'feedback.tpOverFlagged'):kind==='falsePositive'?(decision==='flag'?'feedback.fpFlagged':'feedback.fpPassed'):kind==='falseNegative'?(decision==='flag'?'feedback.fnFound':'feedback.fnMissed'):(decision==='validate'?'feedback.tnConfirmed':'feedback.tnOverFlagged');}
function forensic(){if(!state.selected)return`<aside class="forensic empty"><div class="scan-glyph">◎</div><div><div class="eyebrow">${tx('panel.selected')}</div><h2>${tx('panel.emptyTitle')}</h2><p>${tx('panel.emptyBody')}</p></div></aside>`;const r=regionById(state.selected),review=reviewFor(state,r.id),remaining=MAX_REVIEWS-state.reviews.length,guidance=guide();return`<aside class="forensic"><div class="forensic-head"><div><div class="eyebrow">${tx('panel.selected')} · ${String(r.sample).padStart(2,'0')}</div><h2>${tx(`region.${r.id}`)}</h2><p title="${tx('help.confidenceBody')}">${tx(`panel.ai.${r.ai}`,{value:r.confidence})}</p></div><button class="close" data-action="close" aria-label="Close">×</button></div>${guidance?`<div class="guide"><span>↳</span>${guidance}</div>`:''}<div class="layer-tools">${(['raw','ai','context','focus']as EvidenceLayer[]).map(layer=>`<button data-layer="${layer}" class="${state.evidenceLayer===layer?'active':''}" title="${tx(`tool.${layer}Help`)}">${tx(`tool.${layer}`)}</button>`).join('')}<button data-action="evidence-out" aria-label="${tx('evidence.zoomOut')}">−</button><button data-action="evidence-in" aria-label="${tx('evidence.zoomIn')}">＋</button><label title="${tx('tool.overlayHelp')}">${tx('tool.overlay')}<input type="range" min="0" max="1" step=".05" value="${state.overlay}" data-opacity ${state.evidenceLayer==='raw'?'disabled':''}/><output>${Math.round(state.overlay*100)}%</output></label></div>${evidenceArt(r)}<div class="sample-context"><span>${tx(`surface.${r.surface}`)}</span><span>${tx(`quality.${r.quality}`)}</span><span>${tx(`context.${r.context}`)}</span></div>${review?`<div class="decision-feedback ${review.decision===expectedDecision(r)?'supported':'risk'}"><strong>${tx('decision.recorded')}</strong><p>${tx(feedbackKey(r,review.decision))}</p></div>`:`<div class="decision-area"><p>${tx('decision.capacity',{count:remaining})}</p><div><button data-decision="validate" ${remaining===0?'disabled':''}>✓ ${tx(r.ai==='detected'?'decision.validateFinding':'decision.confirmClear')}</button><button data-decision="flag" ${remaining===0?'disabled':''}>⚑ ${tx(r.ai==='detected'?'decision.flagFinding':'decision.flagMiss')}</button></div></div>`}</aside>`;}
function reference(){if(!helpOpen)return'';return`<aside class="reference-drawer"><div><div class="eyebrow">${tx('help.title')}</div><button data-action="help">×</button></div>${(['confidence','fp','fn','quality','generalisation','focus','human']as const).map(key=>`<details><summary>${tx(`help.${key}`)}</summary><p>${tx(`help.${key}Body`)}</p></details>`).join('')}</aside>`;}
function audit(){const remaining=MAX_REVIEWS-state.reviews.length;return`<div class="blind-shell">${header()}${hud()}<main class="audit-layout">${boardPanel()}${forensic()}</main><footer class="audit-footer"><div>${canMarkConcern(state)?`<button class="concern-action ${state.concernMarked?'active':''}" data-action="concern">${state.concernMarked?'✓ ':''}${tx(state.concernMarked?'pattern.marked':'board.markConcern')}</button>`:`<p>${reviewedMismatchCount(state)===1?tx('pattern.one'):tx('audit.minimum')}</p>`}<small>${tx('audit.remaining',{count:remaining})}</small></div><button data-action="finish" ${!canFinalize(state)?'disabled':''}>${tx('audit.finish')} →</button><em>${tx('footer.note')}</em></footer>${reference()}</div>`;}

function report(){const result=integrity(state),high=reviewFor(state,'p2')?.decision==='flag';return`<div class="blind-shell report-shell">${header()}<main class="report-layout"><section class="report-map"><div class="board-head"><div><div class="eyebrow">${tx('report.eyebrow')}</div><h1>${tx(result.passed?'report.strongTitle':'report.weakTitle')}</h1></div><strong class="integrity-score ${result.passed?'pass':'risk'}">${tx('report.score',{value:result.score})}</strong></div>${building(false)}</section><aside class="report-panel"><p>${tx(result.passed?'report.strongBody':'report.weakBody')}</p><div class="report-grid"><div><strong>${result.validated}</strong><span>${tx('report.validated')}</span></div><div><strong>${result.flagged}</strong><span>${tx('report.flagged')}</span></div><div><strong>${result.falsePositivesPrevented}</strong><span>${tx('report.fp')}</span></div><div><strong>${result.missedFindingsFound}</strong><span>${tx('report.fn')}</span></div><div><strong>${result.reviewRequired}</strong><span>${tx('report.review')}</span></div><div class="${result.unresolved?'risk':''}"><strong>${result.unresolved}</strong><span>${tx('report.unresolved')}</span></div></div><div class="report-signals"><p class="${high?'yes':'no'}">${high?'✓':'!'} ${tx(high?'report.highConfidence':'report.highConfidenceMissed')}</p><p class="${result.blindSpot?'yes':'no'}">${result.blindSpot?'✓':'!'} ${tx(result.blindSpot?'report.pattern':'report.noPattern')}</p><p class="${result.mixedSampling?'yes':'no'}">${result.mixedSampling?'✓':'!'} ${tx(result.mixedSampling?'report.mixed':'report.oneSided')}</p></div><button data-action="revise">${tx('report.revise')}</button><button class="secondary" data-action="replay">${tx('report.replay')}</button></aside></main></div>`;}
function render(){app.innerHTML=state.phase==='intro'?intro():state.phase==='report'?report():audit();}
function choose(id:RegionId){state={...state,selected:id,evidenceLayer:'raw',usedLayers:state.usedLayers.includes('raw')?state.usedLayers:[...state.usedLayers,'raw']};evidenceZoom=1;save();render();}
app.addEventListener('click',event=>{const target=event.target as HTMLElement,region=target.closest<SVGGElement>('[data-region]')?.dataset.region as RegionId|undefined;if(region&&state.phase==='audit'){choose(region);return;}const layer=target.closest<HTMLButtonElement>('[data-layer]')?.dataset.layer as EvidenceLayer|undefined;if(layer){state={...state,evidenceLayer:layer,usedLayers:state.usedLayers.includes(layer)?state.usedLayers:[...state.usedLayers,layer]};save();render();return;}const decision=target.closest<HTMLButtonElement>('[data-decision]')?.dataset.decision as Decision|undefined;if(decision&&state.selected){state=decide(state,state.selected,decision);save();render();return;}const action=target.closest<HTMLButtonElement>('[data-action]')?.dataset.action;if(action==='start'){state={...fresh('audit'),selected:'p1',usedLayers:['raw']};save();render();}else if(action==='close'){state={...state,selected:null};save();render();}else if(action==='help'){helpOpen=!helpOpen;render();}else if(action==='ai-toggle'){state={...state,aiOverlay:!state.aiOverlay};save();render();}else if(action==='board-in'||action==='board-out'){state={...state,boardZoom:Math.max(.9,Math.min(1.3,state.boardZoom+(action==='board-in'?.1:-.1)))};save();render();}else if(action==='evidence-in'||action==='evidence-out'){evidenceZoom=Math.max(1,Math.min(1.8,evidenceZoom+(action==='evidence-in'?.2:-.2)));render();}else if(action==='concern'&&canMarkConcern(state)){state={...state,concernMarked:!state.concernMarked};save();render();}else if(action==='finish'&&canFinalize(state)){const result=integrity(state);state={...state,phase:'report',selected:null};save();scorm.complete(result.score,result.passed);render();window.scrollTo({top:0,behavior:'smooth'});}else if(action==='revise'){state={...state,phase:'audit'};save();render();}else if(action==='replay'){state=fresh('intro');save();render();window.scrollTo({top:0,behavior:'smooth'});}});
app.addEventListener('keydown',event=>{if(!['Enter',' '].includes(event.key))return;const region=(event.target as HTMLElement).closest<SVGGElement>('[data-region]')?.dataset.region as RegionId|undefined;if(region&&state.phase==='audit'){event.preventDefault();choose(region);}});
app.addEventListener('input',event=>{const input=(event.target as HTMLElement).closest<HTMLInputElement>('[data-opacity]');if(!input)return;state={...state,overlay:Number(input.value),overlayAdjusted:true};document.querySelector<SVGElement>('.evidence-art')?.style.setProperty('--overlay',String(state.overlay));const output=input.parentElement?.querySelector('output');if(output)output.textContent=`${Math.round(state.overlay*100)}%`;});app.addEventListener('change',event=>{if((event.target as HTMLElement).matches('[data-opacity]')){save();render();}});window.addEventListener('beforeunload',()=>scorm.finish());render();
